<?php

use Illuminate\Database\Seeder;
use App\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinceColumn = 'province_id';
        $cityColumn = 'name';
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'تبريز']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'كندوان']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'بندر شرفخانه']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'مراغه']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'ميانه']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'شبستر']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'مرند']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'جلفا']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'سراب']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'هاديشهر']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'بناب']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'كليبر']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'تسوج']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'اهر']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'هريس']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'عجبشير']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'هشترود']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'ملكان']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'بستان آباد']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'ورزقان']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'اسكو']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'آذر شهر']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'قره آغاج']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'ممقان']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'صوفیان']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'ایلخچی']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'خسروشهر']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'باسمنج']);
        factory(City::class)->create([$provinceColumn => 1, $cityColumn => 'سهند']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'اروميه']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'نقده']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'ماكو']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'تكاب']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'خوي']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'مهاباد']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'سر دشت']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'چالدران']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'بوكان']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'مياندوآب']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'سلماس']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'شاهين دژ']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'پيرانشهر']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'سيه چشمه']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'اشنويه']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'چایپاره']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'پلدشت']);
        factory(City::class)->create([$provinceColumn => 2, $cityColumn => 'شوط']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'اردبيل']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'سرعين']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'بيله سوار']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'پارس آباد']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'خلخال']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'مشگين شهر']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'مغان']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'نمين']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'نير']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'كوثر']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'كيوي']);
        factory(City::class)->create([$provinceColumn => 3, $cityColumn => 'گرمي']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'اصفهان']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'فريدن']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'فريدون شهر']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'فلاورجان']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'گلپايگان']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'دهاقان']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'نطنز']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'نايين']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'تيران']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'كاشان']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'فولاد شهر']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'اردستان']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'سميرم']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'درچه']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'کوهپایه']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'مباركه']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'شهرضا']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'خميني شهر']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'شاهين شهر']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'نجف آباد']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'دولت آباد']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'زرين شهر']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'آران و بيدگل']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'باغ بهادران']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'خوانسار']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'مهردشت']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'علويجه']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'عسگران']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'نهضت آباد']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'حاجي آباد']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'تودشک']);
        factory(City::class)->create([$provinceColumn => 4, $cityColumn => 'ورزنه']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'ايلام']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'مهران']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'دهلران']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'آبدانان']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'شيروان چرداول']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'دره شهر']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'ايوان']);
        factory(City::class)->create([$provinceColumn => 6, $cityColumn => 'سرابله']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'بوشهر']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'تنگستان']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'دشتستان']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'دير']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'ديلم']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'كنگان']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'گناوه']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'ريشهر']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'دشتي']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'خورموج']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'اهرم']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'برازجان']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'خارك']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'جم']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'کاکی']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'عسلویه']);
        factory(City::class)->create([$provinceColumn => 7, $cityColumn => 'بردخون']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'تهران']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'ورامين']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'فيروزكوه']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'ري']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'دماوند']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'اسلامشهر']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'رودهن']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'لواسان']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'بومهن']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'تجريش']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'فشم']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'كهريزك']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'پاكدشت']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'چهاردانگه']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'شريف آباد']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'قرچك']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'باقرشهر']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'شهريار']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'رباط كريم']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'قدس']);
        factory(City::class)->create([$provinceColumn => 8, $cityColumn => 'ملارد']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'شهركرد']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'فارسان']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'بروجن']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'چلگرد']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'اردل']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'لردگان']);
        factory(City::class)->create([$provinceColumn => 9, $cityColumn => 'سامان']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'قائن']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'فردوس']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'بيرجند']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'نهبندان']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'سربيشه']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'طبس مسینا']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'قهستان']);
        factory(City::class)->create([$provinceColumn => 10, $cityColumn => 'درمیان']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'مشهد']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'نيشابور']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'سبزوار']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'كاشمر']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'گناباد']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'طبس']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'تربت حيدريه']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'خواف']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'تربت جام']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'تايباد']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'قوچان']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'سرخس']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'بردسكن']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'فريمان']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'چناران']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'درگز']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'كلات']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'طرقبه']);
        factory(City::class)->create([$provinceColumn => 11, $cityColumn => 'سر ولایت']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'بجنورد']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'اسفراين']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'جاجرم']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'شيروان']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'آشخانه']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'گرمه']);
        factory(City::class)->create([$provinceColumn => 12, $cityColumn => 'ساروج']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'اهواز']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'ايرانشهر']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'شوش']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'آبادان']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'خرمشهر']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'مسجد سليمان']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'ايذه']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'شوشتر']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'انديمشك']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'سوسنگرد']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'هويزه']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'دزفول']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'شادگان']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'بندر ماهشهر']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'بندر امام خميني']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'اميديه']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'بهبهان']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'رامهرمز']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'باغ ملك']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'هنديجان']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'لالي']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'رامشیر']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'حمیدیه']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'دغاغله']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'ملاثانی']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'شادگان']);
        factory(City::class)->create([$provinceColumn => 13, $cityColumn => 'ویسی']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'زنجان']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'ابهر']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'خدابنده']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'كارم']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'ماهنشان']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'خرمدره']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'ايجرود']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'زرين آباد']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'آب بر']);
        factory(City::class)->create([$provinceColumn => 14, $cityColumn => 'قيدار']);
        factory(City::class)->create([$provinceColumn => 15, $cityColumn => 'سمنان']);
        factory(City::class)->create([$provinceColumn => 15, $cityColumn => 'شاهرود']);
        factory(City::class)->create([$provinceColumn => 15, $cityColumn => 'گرمسار']);
        factory(City::class)->create([$provinceColumn => 15, $cityColumn => 'ايوانكي']);
        factory(City::class)->create([$provinceColumn => 15, $cityColumn => 'دامغان']);
        factory(City::class)->create([$provinceColumn => 15, $cityColumn => 'بسطام']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'زاهدان']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'چابهار']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'خاش']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'سراوان']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'زابل']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'سرباز']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'نيكشهر']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'ايرانشهر']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'راسك']);
        factory(City::class)->create([$provinceColumn => 16, $cityColumn => 'ميرجاوه']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'شيراز']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'اقليد']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'داراب']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'فسا']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'مرودشت']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'خرم بيد']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'آباده']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'كازرون']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'ممسني']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'سپيدان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'لار']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'فيروز آباد']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'جهرم']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'ني ريز']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'استهبان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'لامرد']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'مهر']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'حاجي آباد']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'نورآباد']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'اردكان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'صفاشهر']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'ارسنجان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'قيروكارزين']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'سوريان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'فراشبند']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'سروستان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'ارژن']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'گويم']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'داريون']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'زرقان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'خان زنیان']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'کوار']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'ده بید']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'باب انار/خفر']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'بوانات']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'خرامه']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'خنج']);
        factory(City::class)->create([$provinceColumn => 17, $cityColumn => 'سیاخ دارنگون']);
        factory(City::class)->create([$provinceColumn => 18, $cityColumn => 'قزوين']);
        factory(City::class)->create([$provinceColumn => 18, $cityColumn => 'تاكستان']);
        factory(City::class)->create([$provinceColumn => 18, $cityColumn => 'آبيك']);
        factory(City::class)->create([$provinceColumn => 18, $cityColumn => 'بوئين زهرا']);
        factory(City::class)->create([$provinceColumn => 19, $cityColumn => 'قم']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'طالقان']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'نظرآباد']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'اشتهارد']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'هشتگرد']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'كن']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'آسارا']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'شهرک گلستان']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'اندیشه']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'كرج']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'نظر آباد']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'گوهردشت']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'ماهدشت']);
        factory(City::class)->create([$provinceColumn => 5, $cityColumn => 'مشکین دشت']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'سنندج']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'ديواندره']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'بانه']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'بيجار']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'سقز']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'كامياران']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'قروه']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'مريوان']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'صلوات آباد']);
        factory(City::class)->create([$provinceColumn => 20, $cityColumn => 'حسن آباد']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'كرمان']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'راور']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'بابك']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'انار']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'کوهبنان']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'رفسنجان']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'بافت']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'سيرجان']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'كهنوج']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'زرند']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'بم']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'جيرفت']);
        factory(City::class)->create([$provinceColumn => 21, $cityColumn => 'بردسير']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'كرمانشاه']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'اسلام آباد غرب']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'سر پل ذهاب']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'كنگاور']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'سنقر']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'قصر شيرين']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'گيلان غرب']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'هرسين']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'صحنه']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'پاوه']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'جوانرود']);
        factory(City::class)->create([$provinceColumn => 22, $cityColumn => 'شاهو']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'ياسوج']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'گچساران']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'دنا']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'دوگنبدان']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'سي سخت']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'دهدشت']);
        factory(City::class)->create([$provinceColumn => 23, $cityColumn => 'ليكك']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'گرگان']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'آق قلا']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'گنبد كاووس']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'علي آباد كتول']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'مينو دشت']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'تركمن']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'كردكوي']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'بندر گز']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'كلاله']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'آزاد شهر']);
        factory(City::class)->create([$provinceColumn => 24, $cityColumn => 'راميان']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'رشت']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'منجيل']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'لنگرود']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'رود سر']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'تالش']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'آستارا']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'ماسوله']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'آستانه اشرفيه']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'رودبار']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'فومن']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'صومعه سرا']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'بندرانزلي']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'كلاچاي']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'هشتپر']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'رضوان شهر']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'ماسال']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'شفت']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'سياهكل']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'املش']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'لاهیجان']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'خشک بيجار']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'خمام']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'لشت نشا']);
        factory(City::class)->create([$provinceColumn => 25, $cityColumn => 'بندر کياشهر']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'خرم آباد']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'ماهشهر']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'دزفول']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'بروجرد']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'دورود']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'اليگودرز']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'ازنا']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'نور آباد']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'كوهدشت']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'الشتر']);
        factory(City::class)->create([$provinceColumn => 26, $cityColumn => 'پلدختر']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'ساري']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'آمل']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'بابل']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'بابلسر']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'بهشهر']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'تنكابن']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'جويبار']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'چالوس']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'رامسر']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'سواد كوه']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'قائم شهر']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'نكا']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'نور']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'بلده']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'نوشهر']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'پل سفيد']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'محمود آباد']);
        factory(City::class)->create([$provinceColumn => 27, $cityColumn => 'فريدون كنار']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'اراك']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'آشتيان']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'تفرش']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'خمين']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'دليجان']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'ساوه']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'سربند']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'محلات']);
        factory(City::class)->create([$provinceColumn => 28, $cityColumn => 'شازند']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'بندرعباس']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'قشم']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'كيش']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'بندر لنگه']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'بستك']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'حاجي آباد']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'دهبارز']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'انگهران']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'ميناب']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'ابوموسي']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'بندر جاسك']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'تنب بزرگ']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'بندر خمیر']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'پارسیان']);
        factory(City::class)->create([$provinceColumn => 29, $cityColumn => 'قشم']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'همدان']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'ملاير']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'تويسركان']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'نهاوند']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'كبودر اهنگ']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'رزن']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'اسدآباد']);
        factory(City::class)->create([$provinceColumn => 30, $cityColumn => 'بهار']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'يزد']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'تفت']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'اردكان']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'ابركوه']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'ميبد']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'طبس']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'بافق']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'مهريز']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'اشكذر']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'هرات']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'خضرآباد']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'شاهديه']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'حمیدیه شهر']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'سید میرزا']);
        factory(City::class)->create([$provinceColumn => 31, $cityColumn => 'زارچ']);
    }
}
